[2024-06-09 15:36:32,021][backoff][INFO] - Backing off chat_completion(...) for 0.5s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:32,097][backoff][INFO] - Backing off chat_completion(...) for 0.0s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:32,183][backoff][INFO] - Backing off chat_completion(...) for 0.1s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:32,394][backoff][INFO] - Backing off chat_completion(...) for 0.1s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:32,545][backoff][INFO] - Backing off chat_completion(...) for 2.4s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:32,588][backoff][INFO] - Backing off chat_completion(...) for 1.2s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:33,893][backoff][INFO] - Backing off chat_completion(...) for 2.4s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:35,037][backoff][INFO] - Backing off chat_completion(...) for 9.2s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:36,407][backoff][INFO] - Backing off chat_completion(...) for 4.8s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:41,311][backoff][INFO] - Backing off chat_completion(...) for 3.8s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:45,241][backoff][INFO] - Backing off chat_completion(...) for 6.1s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:45,958][backoff][INFO] - Backing off chat_completion(...) for 0.1s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-09 15:36:46,154][backoff][INFO] - Backing off chat_completion(...) for 1.2s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
