[2024-06-13 07:26:17,702][backoff][INFO] - Backing off chat_completion(...) for 0.0s (aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-13 07:26:17,881][backoff][INFO] - Backing off chat_completion(...) for 0.7s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-13 07:26:18,688][backoff][INFO] - Backing off chat_completion(...) for 0.5s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-13 07:26:19,313][backoff][INFO] - Backing off chat_completion(...) for 2.4s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-13 07:26:21,977][backoff][INFO] - Backing off chat_completion(...) for 9.5s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-13 07:26:31,658][backoff][INFO] - Backing off chat_completion(...) for 3.0s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
[2024-06-13 07:26:34,825][backoff][INFO] - Backing off chat_completion(...) for 53.0s (aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://api.openai.com/v1/chat/completions'))
